/// `BC-02` Membership — term semantics and the end-date calculus.
///
/// Covers `IMPL-417` (the meaning of `startDate` and `endDate`) and
/// `IMPL-418` (deterministic end-date calculation, including the
/// delayed-payment re-derivation) against FROZEN `PRD-005` v1.4.
///
/// `IMPL-418`'s obligation names the cases: *"Month-end and leap-day cases
/// fixed by table; `MM-CFG-009` `true` re-derives the **whole** term;
/// `endDate >= startDate` always."* So the month-end and leap-day cases below
/// are a literal table, computed by hand from `MM-FR-057` rather than from
/// the implementation — a table generated by the code under test proves only
/// that the code agrees with itself.
///
/// The task doc flags `MM-FR-057a` as *"the requirement most likely to be
/// dropped"*: re-deriving only `startDate` leaves a term shorter than the
/// plan sold, and it is silent because the membership still looks valid. That
/// case is tested explicitly.
library;

import 'package:flutter_test/flutter_test.dart';
import 'package:liboora/domain/library/membership/membership.dart';
import 'package:liboora_contracts/liboora_contracts.dart';

// Local-kind dates throughout, matching `DateRange._dateOnly` and
// `Clock.today()`. Business dates in this codebase are local-kind; mixing in
// UTC-kind values would make isBefore/isAfter depend on the runner's offset.
// Tenant-timezone evaluation is MM-FR-061's subject (IMPL-419).
final DateTime _t0 = DateTime(2026, 3, 1);
const _tenant = TenantId('tnt_a');
const _branch = BranchId('brn_a');

MembershipPlan _plan({int durationDays = 30}) => MembershipPlan.create(
  id: 'plan_1',
  tenantId: _tenant,
  branchId: _branch,
  name: 'Plan',
  durationDays: durationDays,
  price: Money.rupees(1200),
  createdAt: _t0,
  createdBy: 'owner_1',
);

Membership _membership({
  DateTime? start,
  int durationDays = 30,
  MembershipStatus status = MembershipStatus.active,
}) {
  final s = start ?? _t0;
  return Membership.fromPlan(
    id: 'mem_1',
    studentRecordId: const StudentRecordId('stu_1'),
    plan: _plan(durationDays: durationDays),
    term: DateRange.days(s, durationDays),
    status: status,
    createdAt: s,
    createdBy: 'owner_1',
    activatedAt: status == MembershipStatus.active ? s : null,
  );
}

DomainError _rejects(void Function() act) {
  try {
    act();
  } on DomainError catch (e) {
    return e;
  }
  fail('Expected a typed DomainError, but the call succeeded.');
}

void main() {
  // ════════════════════════════════════════════════════════════════════
  // IMPL-417 — term semantics
  // Obligation: "endDate is inclusive; the term is a date range, not a
  // timestamp range."
  // ════════════════════════════════════════════════════════════════════
  group('IMPL-417 term semantics', () {
    test(
      'endDate is the INCLUSIVE last business date (MM-FR-055, MM-FR-057)',
      () {
        final m = _membership(start: DateTime(2026, 3, 1), durationDays: 30);

        // MM-FR-057: 1 March + (30 - 1) = 30 March. A 30-day membership
        // starting on the 1st is valid THROUGH the 30th, not the 31st.
        expect(m.startDate, DateTime(2026, 3, 1));
        expect(
          m.endDate,
          DateTime(2026, 3, 30),
          reason:
              'This is the whole content of MM-FR-057 and the classic source '
              'of a customer-visible "my membership ended a day early" '
              'dispute. The underlying DateRange is half-open, so term.end '
              'is 31 March -- a day later than the spec allows.',
        );
      },
    );

    test('the inclusive endDate is what gets published, not the half-open '
        'bound (MM-FR-055)', () {
      final m = _membership(start: DateTime(2026, 3, 1), durationDays: 30);
      expect(
        m.endDate.isBefore(m.term.end),
        isTrue,
        reason:
            'term.end is the exclusive bound. If these were ever equal the '
            'distinction this test exists to protect would have collapsed.',
      );
      expect(m.term.end.difference(m.endDate), const Duration(days: 1));
    });

    test('the last day is inside the term and the next day is not '
        '(MM-FR-055)', () {
      final m = _membership(start: DateTime(2026, 3, 1), durationDays: 30);
      expect(m.isValidOn(m.endDate), isTrue);
      expect(m.isValidOn(m.endDate.add(const Duration(days: 1))), isFalse);
    });

    test('the term is a range of DATES, not timestamps (MM-FR-056)', () {
      final m = _membership(start: DateTime(2026, 3, 1), durationDays: 30);
      for (final d in [m.startDate, m.endDate]) {
        expect(d.hour, 0);
        expect(d.minute, 0);
        expect(d.second, 0);
        expect(d.millisecond, 0);
      }
    });

    test('the term length always equals the plan durationDays (MM-FR-057)', () {
      for (final days in [1, 2, 7, 28, 30, 31, 90, 365, 366]) {
        final m = _membership(durationDays: days);
        expect(
          m.durationDays,
          days,
          reason: 'A term must be exactly as long as the plan sold.',
        );
        // And the inclusive span agrees: end - start + 1 == durationDays.
        final span = m.endDate.difference(m.startDate).inDays + 1;
        expect(span, days, reason: 'Inclusive span for durationDays=$days.');
      }
    });

    test('endDate >= startDate always, including a single-day plan '
        '(MM-FR-056)', () {
      for (final days in [1, 2, 30, 365]) {
        final m = _membership(durationDays: days);
        expect(
          m.endDate.isBefore(m.startDate),
          isFalse,
          reason: 'MM-INV-002 forbids endDate < startDate.',
        );
      }
      // MM-GAP-008 is OPEN (Architecture Owner): BC Map writes the invariant
      // as strictly `validUntil > validFrom`, and a single-day plan yields
      // endDate == startDate, which satisfies >= but not >. This test asserts
      // the >= that MM-FR-056 states, and deliberately does NOT decide the
      // gap in either direction.
      final single = _membership(durationDays: 1);
      expect(single.endDate, single.startDate);
    });
  });

  // ════════════════════════════════════════════════════════════════════
  // IMPL-418 — deterministic end-date calculation
  // ════════════════════════════════════════════════════════════════════
  group('IMPL-418 end-date calculation', () {
    test('month-end and leap-day cases, fixed by table (MM-FR-057)', () {
      // (startDate, durationDays, expected endDate). Every expected value
      // is computed by hand from MM-FR-057: start + (duration - 1).
      const cases = <(DateTime, int, DateTime)>[];
      final table = <(DateTime, int, DateTime)>[
        // 31-day month.
        (DateTime(2026, 1, 1), 31, DateTime(2026, 1, 31)),
        // Crossing a month end.
        (DateTime(2026, 1, 15), 31, DateTime(2026, 2, 14)),
        // Into a 28-day February (2026 is not a leap year).
        (DateTime(2026, 2, 1), 28, DateTime(2026, 2, 28)),
        (DateTime(2026, 2, 1), 30, DateTime(2026, 3, 2)),
        // A 31st start into a 30-day month.
        (DateTime(2026, 3, 31), 31, DateTime(2026, 4, 30)),
        // Leap year: 2028 February has 29 days.
        (DateTime(2028, 2, 1), 29, DateTime(2028, 2, 29)),
        (DateTime(2028, 2, 28), 2, DateTime(2028, 2, 29)),
        (DateTime(2028, 2, 29), 1, DateTime(2028, 2, 29)),
        // Crossing 29 Feb in a leap year.
        (DateTime(2028, 2, 15), 30, DateTime(2028, 3, 15)),
        // And the same window in a NON-leap year is a day earlier in March.
        (DateTime(2026, 2, 15), 30, DateTime(2026, 3, 16)),
        // Year boundary.
        (DateTime(2026, 12, 15), 31, DateTime(2027, 1, 14)),
        (DateTime(2026, 12, 31), 1, DateTime(2026, 12, 31)),
        // A full year.
        (DateTime(2026, 1, 1), 365, DateTime(2026, 12, 31)),
        // A full leap year.
        (DateTime(2028, 1, 1), 366, DateTime(2028, 12, 31)),
      ];
      expect(cases, isEmpty); // keeps the const declaration honest
      expect(table, isNotEmpty, reason: 'Vacuity guard.');

      for (final (start, days, expected) in table) {
        expect(
          Membership.endDateFor(start, days),
          expected,
          reason: 'endDateFor($start, $days) must be $expected per MM-FR-057.',
        );
        // And the aggregate agrees with the pure function.
        final m = _membership(start: start, durationDays: days);
        expect(m.endDate, expected, reason: 'Aggregate for $start/$days.');
      }
    });

    test('the calculation is a PURE function of its inputs (MM-FR-058)', () {
      // Same inputs, many calls, over a changing wall clock: same answer.
      final a = Membership.endDateFor(DateTime(2026, 3, 1), 30);
      for (var i = 0; i < 50; i++) {
        expect(Membership.endDateFor(DateTime(2026, 3, 1), 30), a);
      }

      // It is static, so it cannot read instance state, and it takes no
      // Clock -- MM-FR-058 forbids depending on the current clock, on
      // holidays, or on a working calendar.
      expect(a, DateTime(2026, 3, 30));
    });

    test('a duration below 1 is rejected rather than producing a '
        'backwards term (MM-FR-056)', () {
      for (final bad in [0, -1, -30]) {
        final e = _rejects(
          () => Membership.endDateFor(DateTime(2026, 3, 1), bad),
        );
        expect(e.code, DomainErrorCode.validationFailed);
        expect(e.context['durationDays'], bad);
      }
    });

    test('a time component on the input does not shift the computed date '
        '(MM-FR-056)', () {
      // Late-evening input must not roll the answer into the next day.
      expect(
        Membership.endDateFor(DateTime(2026, 3, 1, 23, 59, 59), 30),
        DateTime(2026, 3, 30),
      );
      expect(
        Membership.endDateFor(DateTime(2026, 3, 1, 0, 0, 1), 30),
        DateTime(2026, 3, 30),
      );
    });
  });

  // ════════════════════════════════════════════════════════════════════
  // IMPL-418 — MM-FR-057a, the delayed-payment re-derivation
  // ════════════════════════════════════════════════════════════════════
  group('IMPL-418 MM-FR-057a re-derivation', () {
    test('MM-CFG-009 re-derives the WHOLE term, not just startDate '
        '(MM-FR-057a)', () {
      // Sold for 1 March, 30 days. Payment lands on 10 March.
      const durationDays = 30;
      final activation = DateTime(2026, 3, 10);

      final reDerived = Membership.reDerivedTerm(
        activationDate: activation,
        durationDays: durationDays,
      );

      expect(reDerived.start, DateTime(2026, 3, 10));
      expect(
        reDerived.end.subtract(const Duration(days: 1)),
        DateTime(2026, 4, 8),
        reason: '10 March + (30 - 1) = 8 April, by MM-FR-057 unchanged.',
      );
    });

    test('the re-derived term is exactly as long as the one sold — the '
        'silent-shortening failure the task doc flags (MM-FR-057)', () {
      for (final days in [1, 7, 30, 90, 365]) {
        final original = DateRange.days(DateTime(2026, 3, 1), days);
        final reDerived = Membership.reDerivedTerm(
          activationDate: DateTime(2026, 3, 10),
          durationDays: days,
        );
        expect(
          reDerived.lengthInDays,
          original.lengthInDays,
          reason:
              'Re-deriving only startDate would leave a term SHORTER than '
              'the plan sold, and it is silent because the membership still '
              'looks valid. durationDays=$days.',
        );
        expect(reDerived.lengthInDays, days);
      }
    });

    test('moving endDate while holding startDate fixed is not offered '
        '(MM-FR-057a)', () {
      // MM-FR-057a: that operation "MUST be impossible, because it would
      // yield a term longer than durationDays". The API expresses it as a
      // whole new term from a new startDate -- there is no setter for one
      // endpoint, so the unlawful shape cannot be written.
      final reDerived = Membership.reDerivedTerm(
        activationDate: DateTime(2026, 3, 10),
        durationDays: 30,
      );
      expect(reDerived, isA<DateRange>());
      expect(reDerived.start, DateTime(2026, 3, 10));
    });

    test('re-derivation stays a pure function of (activationDate, '
        'durationDays) (MM-FR-058)', () {
      final a = Membership.reDerivedTerm(
        activationDate: DateTime(2026, 3, 10),
        durationDays: 30,
      );
      final b = Membership.reDerivedTerm(
        activationDate: DateTime(2026, 3, 10, 18, 45),
        durationDays: 30,
      );
      expect(
        b.start,
        a.start,
        reason:
            'The activation timestamp is normalised to its calendar date, '
            'so the hour a payment happens to land cannot change the term.',
      );
      expect(b.end, a.end);
    });

    test('MM-CFG-009 defaults to false — re-derivation is opt-in', () {
      const cfg = DefaultMembershipConfig();
      expect(
        cfg.reDeriveTermOnDelayedActivation,
        isFalse,
        reason:
            'MM-FR-057a applies only when MM-CFG-009 is enabled. The default '
            'must not silently re-derive terms.',
      );
      const enabled = DefaultMembershipConfig(
        reDeriveTermOnDelayedActivation: true,
      );
      expect(enabled.reDeriveTermOnDelayedActivation, isTrue);
    });
  });

  // ════════════════════════════════════════════════════════════════════
  // Regression guard for the renewal arithmetic this fix unblocks
  // ════════════════════════════════════════════════════════════════════
  group('endDate feeds the renewal calculus (MM-FR-085)', () {
    test(
      'a renewal starting endDate + 1 day does NOT overlap the old term',
      () {
        final current = _membership(
          start: DateTime(2026, 3, 1),
          durationDays: 30,
        );

        // MM-FR-085 derives the successor's startDate from endDate + 1 day.
        final renewalStart = current.endDate.add(const Duration(days: 1));
        expect(renewalStart, DateTime(2026, 3, 31));

        final renewalTerm = DateRange.days(renewalStart, 30);
        expect(
          current.term.overlaps(renewalTerm),
          isFalse,
          reason:
              'This is why the inclusive endDate matters. Derived from the '
              'half-open term.end (31 March) the renewal would start on 1 '
              'April, leaving 31 March uncovered -- a paying student locked '
              'out for a day.',
        );

        // And there is no gap either: the renewal starts the day after the
        // last covered day.
        expect(
          renewalStart.difference(current.endDate),
          const Duration(days: 1),
        );
      },
    );
  });
}
